### ISSUE TITLE
Notes for quickly getting a DLL list from Process Explorer using Visual Studio REGEX

### ISSUE THREAD

**Issue by Mou-Ikkai** [lawndoc/winbin.wtf#11]
# Export DLLs
![exportDLLfile](https://user-images.githubusercontent.com/45863583/193981294-eec6de62-cd4b-435d-bf30-9152c8d23585.gif)

# Edit Export for Markdown
![howtoReplace](https://user-images.githubusercontent.com/45863583/193981746-484df057-7534-47a9-8e14-da4181849aeb.gif)

## Setup
Ctrl+H
Enable `Use Regular Expressions`

## Clearing all non-DLL files
Find: `^(?:(?!^.*\.dll\s).)*$`
Leave Replace box empty and press "Replace all"

## Format start of each line with Markdown for template.
Find: `^.*(?=C:)`
Replace Box: 
```
    - 
```

**Comment by Mou-Ikkai** [comment]
This is simply a note for anyone wishing to quickly get a DLL list from a program with proper formatting.

**Comment by Mou-Ikkai** [comment]
@lawndoc I hope this helps when you add your own submissions! :3

**Comment by Mou-Ikkai** [comment]
Updated 1st regex to now also remove .dll.mui files.

**Comment by lawndoc** [comment]
I moved this documentation to the [Contributing Tips wiki page]. Thanks for the detail and GIFs!
