### ISSUE TITLE
Addition to template: Command Executable.

### ISSUE THREAD

**Issue by VocalFan** [lawndoc/winbin.wtf#19]
There are many executables in Windows that only function within the command line, such as DiskPart, ipconfig, help, ktmutil, and so on. Maybe we should include if a program is made to be run in CMD?

`Command: False #An executable made to only be run using the Command Prompt`

**Comment by lawndoc** [comment]
How about `GUI` rather than `Command`? That might be a little less ambiguous.

**Comment by Mou-Ikkai** [comment]
Sure!
